name: Build and save my Docker image to a registry

on:
  push:
    branches:
      - main  # Déclenchement lorsque le code est poussé sur main
    paths:
      - 'src/backend/**'
env:
  REG_NAME: "acrinfofd22210.azurecr.io" # Nom du registy
  IMAGE_NAME: "todo-backend-matias" # Nom de votre image

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REG_NAME }}
          username: ${{ secrets.AZURE_REGISTRY_USER }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.REG_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ./src/backend

      - name: Push Docker image
        run: |
          docker push ${{ env.REG_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
